### ISSUE TITLE
DirectionsService vs Distance Matrix

### ISSUE THREAD

**Issue by jherrlin** [rk222ev/trains#1]
Tror att vi ska kika på Distance Matrix istället för DirectionsService, DIrectionsService verkar visa aktuella routes beroende på tid punk och när tåg och så går, fick upp riktigt skumma saker inatt.
Osby -> Alvesta, ville då först åka till Hässleholm för att DirectionService ansåg att det var bäst och minst transfers :/

**Comment by rk222ev** [comment]
Vekar ha löst sig med den satta tidpunkten. Stänger issuen.
